#语言文件
Lang: zh_cn

#该服务器的名字，用于替换%server%
ThisServerName: "§e§l大厅"

#前缀发送跨服聊天 设置为false禁止,默认为"true"
ChatPrefixEnable: true
#跨服说话的前缀
ChatPrefix: "!"
#跨服说话冷却时间(/秒)
#ChatCoolTime: 30

#喇叭的有效时间(/秒)
ItemResponTime: 30

CoolTime: 30

ItemNoCoolTime: true

CommandBuyItem: true

ItemBuyMenu: true

FreeChat: false

AutoUse: true

AutoCost: true

ItemSet:
  NoCoolTime: true
  AllowCommandBuy: true
  BuyMenu: true
  ResponTime: 30
Cost:
  Enable: true
  Money: 50
  PlayerPoint: 10

###########################################
###############BOSS血条配置################
###########################################

#设置"false"为禁止.1.9以下请关闭这个！否则会报错
BossBar: false

##Boss血条的颜色
BossBarColor: GREEN

##Boss血条的风格
BossBarStyle: SOLID

BossBarFlags:[]

#BossBar持续时间(/秒)
BossBarContinued: 6

BossBarMessage: "%server% §a§l%player% §7如此说道: §r%message%"


###############################################
###############ActionBar配置############
###############################################

#设置"false"为禁止
ActionBar: true

ActionBarMessage: "§a§l%player% : %message%"


#####################################
###########聊天栏配置##############
#####################################

#在聊天栏中发送跨服消息 设置为"false"禁用
Chat: true

ChatMessage: "§7<%server%§7> §a§l%player% §7says §r%message%"
##########################################

##跨服说话长度限制
LenthLimit:
  #最短
  Min: 0
  #最长
  Max: 40

##脏话屏蔽
ShieldMessages:
  - "操你妈"
  - "傻逼"
  - "干你妈"
  - "有病"
  - "畜生"
  - "禽兽"
  - "人兽"
  - "你妈"
  - "他妈"
  - "脑残"
  - "操"
  - "fuck"
  - "shit"
  - "bitch"
##脏话替换的字符
ShieldReplaces: "♥"
  
#别碰他！
ConfigVersion: 1