api-version: 1.13
name: ServerChat
version: 1.7.1.1
author: Zao_hon
main: cn.blockmc.Zao_hon.ServerChat.ServerChat
softdepends: [AuthMe,LoginSecurity,Vault,PlayerPoint]
commands:
    ServerChat:
        aliases: [sc,sch]
Permissions:
    ServerChat.Admin:
        default: op
    ServerChat.Ignore:
        default: op
    ServerChat.Color:
        default: op
    ServerChat.Buy:
        default: All