api-version: 1.13
name: ServerChat
version: 1.6.7
author: Zao_hon
main: cn.blockmc.Zao_hon.Bukkit.ServerChat
softdepends: [AuthMe,LoginSecurity]
commands:
    ServerChat:
        aliases: [sc]
Permissions:
    ServerChat.Admin:
        default: op
    ServerChat.Ignore:
        default: op